version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'products_db'
    volumes:
      - ./mydb:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080