"""empty message

Revision ID: 4b1753851fb9
Revises: 3b53da2a3d20
Create Date: 2022-05-19 13:29:17.095088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b1753851fb9'
down_revision = '3b53da2a3d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwords', sa.String(length=255), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('user', 'passwords')
    # ### end Alembic commands ###
