"""empty message

Revision ID: 524eec2ed64d
Revises: 4b1753851fb9
Create Date: 2022-05-19 13:29:29.704759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '524eec2ed64d'
down_revision = '4b1753851fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('user', 'passwords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwords', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
